export const brand = {
  name: '6ix to Go',
  logo: '/brand/logo-black.png',
  logoColour: '/brand/logo-colour.svg',
  email: 'krishj57@gmail.com',
  phone: '8108200988',
  address: 'D-5, RSC Rd Number 32, CHS, Samabhav Society, Gorai 2, Borivali West, Mumbai, Maharashtra 400091',
  currency: 'INR',
  instagram: '',
};

export const navGroups = [
  { label: 'NEW', href: '/collections/new-arrivals' },
  { label: 'SHOP', items: [
    { label: 'SHOP ALL', href: '/collections/shop-all' },
    { label: 'T-SHIRTS', href: '/collections/t-shirts' },
    { label: 'POLOS', href: '/collections/polos' },
    { label: 'JERSEYS', href: '/collections/jerseys' },
    { label: 'SHIRTS', href: '/collections/shirts' }
  ]},
  { label: 'THE 6IX', href: '/collections/drop-01' },
  { label: 'BRAND', items: [
    { label: 'ABOUT 6IX TO GO', href: '/about' },
    { label: 'THE STORY', href: '/story' },
    { label: 'OUR PHILOSOPHY', href: '/philosophy' },
    { label: 'SIGN UP', href: '/signup' }
  ]}
];

export const collections = [
  { slug: 'new-arrivals', title: 'New Arrivals', image: '/images/products/the-bloodline/1.webp' },
  { slug: 'shop-all', title: 'Shop All', image: '/images/products/the-number-one/1.webp' },
  { slug: 'drop-01', title: 'The 6ix — Drop 01', image: '/images/products/the-starter/3.webp' },
  { slug: 't-shirts', title: 'T-Shirts', image: '/images/products/the-ride/1.webp' },
  { slug: 'polos', title: 'Polos', image: '/images/products/the-bloodline/1.webp' },
  { slug: 'jerseys', title: 'Jerseys', image: '/images/products/the-starter/3.webp' },
  { slug: 'shirts', title: 'Shirts', image: '/images/products/the-regrettucine/4.webp' }
];

const gallery = slug => [1,2,3,4,5].map(n => `/images/products/${slug}/${n}.webp`);
const standardSizes = ['S','M','L','XL','XXL'];
export const products = [
  { slug:'the-bloodline', title:'The Bloodline', productType:'Maroon Polo', price:1499, compareAt:null, category:'polos', collections:['new-arrivals','shop-all','drop-01','polos'], available:true, badge:'NEW', images:gallery('the-bloodline'), sizes:standardSizes, material:'Cotton poly blend', description:"Some stories are inherited. Others are rewritten. The Bloodline blends classic polo styling with 6ix To Go's expressive identity, creating a premium everyday piece that carries a sense of legacy, individuality and modern street culture.", details:['Cotton poly blend'], color:'Maroon', care:'' },
  { slug:'the-wild-card', title:'The Wild Card', productType:'White Polo', price:1499, compareAt:null, category:'polos', collections:['new-arrivals','shop-all','drop-01','polos'], available:true, badge:'NEW', images:gallery('the-wild-card'), sizes:standardSizes, material:'Cotton poly blend', description:"You can't predict the move and that's exactly the point. The Wild Card brings a clean, versatile streetwear look with a little edge, designed for the person who changes the vibe without changing who they are.", details:['Cotton poly blend'], color:'White', care:'' },
  { slug:'the-number-one', title:'The Number One', productType:'White Tee', price:1399, compareAt:null, category:'t-shirts', collections:['new-arrivals','shop-all','drop-01','t-shirts'], available:true, badge:'NEW', images:gallery('the-number-one'), sizes:standardSizes, material:'100% pure cotton', description:'For the one who never waits for permission. The Number One is a confident 6ix To Go statement piece, bringing colour, character and everyday comfort together in a relaxed streetwear fit. Wear it like your position is already decided.', details:['100% pure cotton'], color:'White', care:'Gentle wash. Tumble dry only. Medium iron. Do not bleach. Do not dry clean.' },
  { slug:'the-ride', title:'The Ride', productType:'Yellow Tee', price:1399, compareAt:null, category:'t-shirts', collections:['new-arrivals','shop-all','drop-01','t-shirts'], available:true, badge:'NEW', images:[1,2,3,4].map(n => `/images/products/the-ride/${n}.webp`), sizes:standardSizes, material:'Terry cotton', description:'No story stays still. The Ride captures the energy of moving through the city, mixing playful graphics with a relaxed streetwear attitude. A statement everyday tee made for spontaneous plans, long rides and wherever the day takes you.', details:['Terry cotton'], color:'Yellow', care:'' },
  { slug:'the-starter', title:'The Starter', productType:'Blue Jersey', price:1599, compareAt:null, category:'jerseys', collections:['new-arrivals','shop-all','drop-01','jerseys'], available:true, badge:'NEW', images:[3,1,2,4,5].map(n => `/images/products/the-starter/${n}.webp`), sizes:['XS','S','M','L','XL'], material:'Cotton poly blend', description:'Every story needs a first move. The Starter is the easy-going essential that kicks off your 6ix To Go journey — bold enough to stand out, effortless enough to wear on repeat. Made for everyday street style with a playful 6ix To Go attitude.', details:['Cotton poly blend'], color:'Blue', care:'' },
  { slug:'the-regrettucine', title:'The Regrettucine', productType:'Blue Work Shirt', price:2599, compareAt:null, category:'shirts', collections:['new-arrivals','shop-all','drop-01','shirts'], available:true, badge:'NEW', images:[4,5,1,2,3].map(n => `/images/products/the-regrettucine/${n}.webp`), sizes:['MADE TO MEASURE'], material:'Cotton linen blend', description:"A statement layer for the moments you almost changed your mind but didn't. The Regrettucine brings 6ix To Go's playful storytelling into an easy-to-style streetwear silhouette, built for everyday city fits, late-night plans and unapologetic choices.", details:['Cotton linen blend'], color:'Blue', care:'' }
];

export const campaigns = [
  { eyebrow:'DROP 01', title:'6IX PRODUCTS. ONE DROP.', body:'6ix pieces. 6ix ideas. 6ix chances to wear something different.', href:'/collections/drop-01', image:'/images/products/the-starter/3.webp' },
  { eyebrow:'ABOUT 6IX TO GO', title:'BRINGING THE 2000S BACK TO INDIA', body:'Inspired by LA. Built in India. Made for a generation that wants to stand apart.', href:'/about', image:'/images/products/the-ride/3.webp' }
];

export const homeMedia = { desktopVideo:'/media/home-desktop.mp4', mobileVideo:'/media/home-mobile.mp4' };

export const editorialImages = [
  '/images/products/the-number-one/4.webp',
  '/images/products/the-starter/4.webp',
  '/images/products/the-bloodline/3.webp'
];

export const sizeChart = [];

export const policies = {
  "refund-policy": {
    "title": "Return, Exchange & Refund Policy",
    "body": [
      "At 6ix to Go, we want you to love what you ordered.",
      "Because our products are released as carefully curated drops, we follow a specific return and exchange process to protect product quality, hygiene, availability, and the integrity of our limited collections.",
      "Please read this policy carefully before placing an order.",
      "1. Eligibility for Returns and Exchanges",
      "Products may be eligible for return or exchange only if they meet the conditions specified in this policy.",
      "To be eligible:",
      "The product must be unused and unworn.",
      "The product must not have been washed, altered, damaged, stained, or otherwise used.",
      "All original tags, labels, packaging, and accessories must remain attached and intact.",
      "The product must be returned in its original condition.",
      "The product must not show signs of wear, odour, washing, ironing, alteration, or damage.",
      "The return/exchange request must be raised within 7  days of delivery.",
      "Products that do not meet these conditions may be rejected following inspection.",
      "2. Return Window",
      "Customers must raise a return or exchange request within 7 days from the date of delivery.",
      "Requests submitted after the applicable return window may not be accepted.",
      "The date of delivery recorded by our logistics partner will generally be used to determine the applicable return period.",
      "3. Exchange Policy",
      "If exchanges are offered, customers may request an exchange for:",
      "A different size of the same product; or",
      "Another eligible variant, subject to availability.",
      "Exchanges are subject to stock availability.",
      "If the requested replacement size or product is unavailable, 6ix to Go may offer another available resolution in accordance with applicable law and the circumstances of the order.",
      "4. Size Exchanges",
      "We strongly recommend reviewing the size chart available on the product page before placing an order.",
      "If you order the wrong size and the product otherwise meets our return conditions, a size exchange may be available subject to the applicable exchange window and stock availability.",
      "Customers are responsible for selecting the correct size.",
      "5. Products Not Eligible for Return or Exchange",
      "Unless required otherwise under applicable law, the following may not be eligible for return or exchange:",
      "Products that have been worn or washed.",
      "Products with removed or damaged tags.",
      "Products that have been altered or modified.",
      "Products damaged after delivery due to customer handling.",
      "Products showing stains, odour, marks, or signs of use.",
      "Products returned without original packaging where the packaging is required for verification.",
      "Products returned after the applicable return period.",
      "Products specifically identified on the product page as non-returnable or final sale, subject to applicable law.",
      "6. Sale and Limited-Drop Products",
      "Products purchased during special sales, clearance events, promotional campaigns, or limited drops may be subject to separate return or exchange conditions.",
      "Any special return or exchange restriction applicable to a product will be communicated on the relevant product page or at checkout.",
      "Nothing in this policy is intended to exclude any rights or remedies that cannot legally be excluded under applicable law.",
      "7. Damaged, Defective or Incorrect Products",
      "If you receive:",
      "a damaged product,",
      "a manufacturing defect,",
      "an incorrect product,",
      "an incorrect size due to an order-processing error, or",
      "a product materially different from what you ordered,",
      "please contact us  within 48 hours / 2 days of delivery.",
      "Please include:",
      "Your order number.",
      "A description of the issue.",
      "Clear photographs of the product.",
      "Photographs of the packaging and shipping label, where applicable.",
      "A video, where reasonably requested for verification.",
      "Our team will review the claim and determine the appropriate resolution.",
      "8. Quality Inspection",
      "All returned products may be inspected before an exchange, refund, or other resolution is approved.",
      "6ix to Go reserves the right to reject a return where the product does not meet the conditions described in this policy.",
      "9. Return Shipping",
      "Return shipping arrangements and charges will depend on the reason for the return.",
      "Where the return is due to a confirmed manufacturing defect, incorrect product, or other issue attributable to 6ix to Go, 6ix to Go will determine the appropriate return-shipping resolution.",
      "Where the return is due to a change of mind, incorrect size selection, or another reason attributable to the customer, return shipping charges may apply.",
      "The exact process will be communicated when the return request is approved.",
      "10. Refunds",
      "Where a refund is approved, the refund will generally be initiated after the returned product has been received and successfully inspected.",
      "Refund timelines may vary depending on the payment method, banking institution, payment gateway, and other financial intermediaries.",
      "Refunds will generally be processed to the original payment method, unless another method is required or permitted under applicable law.",
      "11. COD Orders",
      "For Cash on Delivery orders, if a refund is approved, customers may be required to provide accurate bank account or other payment details necessary to process the refund.",
      "6ix to Go will not be responsible for delays caused by incorrect refund information supplied by the customer.",
      "12. Return Request Process",
      "To request a return or exchange:",
      "Step 1: Contact krishj57@gmail.com.",
      "Step 2: Provide your order number and relevant details.",
      "Step 3: Provide photographs or other information requested by our team.",
      "Step 4: Wait for return approval and instructions.",
      "Step 5: Pack the product securely in accordance with the instructions provided.",
      "Step 6: Hand over the package to the designated courier or return partner.",
      "Step 7: Once received, the product will undergo inspection.",
      "Step 8: If approved, the applicable exchange or refund will be processed.",
      "13. Cancellation",
      "If you wish to cancel an order, contact us as soon as possible at krishj57@gmail.com.",
      "Cancellation may only be possible before the order has been processed or dispatched.",
      "Once an order has been dispatched, it may no longer be possible to cancel it and the customer may need to follow the applicable return process.",
      "14. Fraudulent or Abusive Return Activity",
      "6ix to Go reserves the right to investigate suspicious, fraudulent, or abusive return activity.",
      "This may include repeated claims involving materially different products, repeated failed deliveries, excessive returns, manipulated products, or other conduct that reasonably indicates misuse of the return system.",
      "Any action taken will be subject to applicable law.",
      "15. Consumer Rights",
      "Nothing in this Return, Exchange & Refund Policy is intended to limit or exclude any consumer right or remedy that cannot legally be excluded under applicable Indian law."
    ]
  },
  "privacy-policy": {
    "title": "Privacy Policy",
    "body": [
      "6ix to Go (\"6ix to Go\", \"we\", \"us\", or \"our\") respects your privacy and is committed to protecting the personal information you share with us.",
      "This Privacy Policy explains how we collect, use, disclose, store, and protect information when you visit or use our website, place an order, create an account, contact us, subscribe to communications, or otherwise interact with 6ix to Go.",
      "By using our website, you acknowledge that you have read and understood this Privacy Policy.",
      "1. Information We Collect",
      "Depending on how you interact with 6ix to Go, we may collect information including:",
      "Information you provide directly",
      "This may include:",
      "Full name",
      "Email address",
      "Mobile number",
      "Billing address",
      "Shipping address",
      "City, state and PIN code",
      "Order information",
      "Product preferences",
      "Customer support communications",
      "Feedback, reviews, and other information you voluntarily provide",
      "Payment information",
      "Payments may be processed through third-party payment gateways.",
      "6ix to Go generally does not store complete debit card, credit card, banking credentials, or other sensitive payment credentials on its own systems unless specifically stated otherwise.",
      "Payment information may be collected and processed by authorised payment service providers according to their respective privacy policies and security practices.",
      "Automatically collected information",
      "When you visit our website, certain technical information may be collected automatically, including:",
      "IP address",
      "Browser type",
      "Device information",
      "Operating system",
      "Pages visited",
      "Referring pages",
      "Approximate location information",
      "Website interaction information",
      "Cookies and similar technologies",
      "Date and time of access",
      "2. How We Use Your Information",
      "We may use information collected from you to:",
      "Process and fulfil orders.",
      "Deliver products.",
      "Process payments.",
      "Provide order confirmations and updates.",
      "Provide customer support.",
      "Process returns, exchanges, cancellations, and refunds.",
      "Improve our products and services.",
      "Improve website functionality and user experience.",
      "Prevent fraud and misuse.",
      "Maintain website security.",
      "Communicate important service-related information.",
      "Send promotional communications where permitted and where applicable consent or other lawful basis exists.",
      "Understand customer preferences and website usage.",
      "Comply with legal, regulatory, tax, accounting, and law-enforcement requirements.",
      "Measure marketing performance.",
      "Improve website functionality.",
      "Provide relevant advertising where applicable.",
      "3. Marketing Communications",
      "If you subscribe to our newsletter, SMS, WhatsApp, or other marketing communications, we may use your contact information to send information about new drops, products, offers, campaigns, events, and 6ix to Go updates, subject to applicable law.",
      "You may opt out of promotional communications at any time using the unsubscribe mechanism provided in the communication or by contacting us",
      "Transactional and service-related communications may continue where reasonably necessary to fulfil an order or provide a service.",
      "4. Sharing of Information",
      "We may share relevant information with trusted service providers where necessary to operate our business.",
      "These may include:",
      "Payment gateway providers.",
      "Shipping and logistics providers.",
      "Website hosting providers.",
      "E-commerce technology providers.",
      "Analytics and technology providers.",
      "Customer support providers.",
      "Marketing and communication service providers.",
      "Professional advisers.",
      "Legal, regulatory, governmental, or law-enforcement authorities where required or permitted by law.",
      "We do not sell your personal information merely because you visit our website.",
      "5. Third-Party Services",
      "Our website may integrate with third-party services, including payment processors, logistics providers, analytics services, social media services, advertising platforms, and other technology providers.",
      "These third parties may process information according to their own privacy policies and applicable legal requirements.",
      "6ix to Go is not responsible for the privacy practices of independent third-party websites or services that are not controlled by us.",
      "6. Data Security",
      "We take reasonable technical and organisational measures designed to protect personal information against unauthorised access, misuse, loss, alteration, or disclosure.",
      "However, no online transmission or storage system can be guaranteed to be completely secure.",
      "Accordingly, while we take reasonable steps to protect information, we cannot guarantee absolute security.",
      "7. Data Retention",
      "We retain personal information only for as long as reasonably necessary for the purposes described in this Privacy Policy, including fulfilling orders, providing customer support, maintaining business and financial records, resolving disputes, preventing fraud, and complying with applicable legal obligations.",
      "Retention periods may vary depending on the type and purpose of the information.",
      "8. Children's Privacy",
      "Our website is not intended to knowingly collect personal information from children where such collection is restricted under applicable law.",
      "If you believe that a child has provided personal information to us in circumstances where such collection is not permitted, please contact us",
      "9. Your Privacy Rights",
      "Subject to applicable law and its effective provisions, you may have rights relating to your personal data, including rights to access, correction, updating, withdrawal of consent where applicable, grievance redressal, and other rights provided under applicable data protection law.",
      "Requests may be submitted to:",
      "krishj57@gmail.com",
      "We may need to verify your identity before processing certain requests.",
      "We will review and respond to privacy-related requests in accordance with applicable law.",
      "10. Changes to this Privacy Policy",
      "We may update this Privacy Policy from time to time to reflect changes in our business, technology, legal requirements, or privacy practices.",
      "The updated version will be posted on this page with a revised \"Last Updated\" date.",
      "We encourage you to periodically review this page.",
      "11. Contact Us",
      "If you have questions about this Privacy Policy or how 6ix to Go handles personal information, please contact:",
      "6ix to Go"
    ]
  },
  "terms-of-service": {
    "title": "Terms & Conditions",
    "body": [
      "Welcome to 6ix to Go.",
      "These Terms & Conditions (\"Terms\") govern your access to and use of the 6ix to Go website and your purchase of products through the website.",
      "By accessing the website, creating an account, placing an order, or otherwise using our services, you agree to be bound by these Terms.",
      "If you do not agree with these Terms, please do not use the website.",
      "1. About 6ix to Go",
      "The website is operated by:",
      "Legal Business Name: [LEGAL ENTITY NAME]",
      "Brand Name: 6ix to Go",
      "Registered Address: D-5, RSC Rd Number 32, CHS, Samabhav Society, Gorai 2, Borivali West, Mumbai, Maharashtra 400091",
      "GSTIN: [GSTIN]",
      "Email: krishj57@gmail.com",
      "Customer Support: 8108200988",
      "6ix to Go is a clothing and streetwear brand offering products through its online platform.",
      "2. Eligibility",
      "By using this website, you represent that:",
      "You are legally capable of entering into a binding agreement under applicable law; and",
      "The information you provide is accurate and complete.",
      "If you are accessing the website on behalf of another person or entity, you represent that you are authorised to do so.",
      "3. Products and Product Information",
      "We make reasonable efforts to ensure that product descriptions, photographs, colours, sizing information, prices, and other product details displayed on the website are accurate.",
      "However, colours may appear differently depending on your device, display settings, lighting, photography, and other factors.",
      "Minor variations in colour, print placement, texture, measurements, and finish may occur.",
      "Such variations do not necessarily constitute a product defect.",
      "4. Pricing",
      "All prices displayed on the website are in Indian Rupees (INR), unless otherwise stated.",
      "Applicable taxes will be displayed as required by law.",
      "6ix to Go reserves the right to modify product prices at any time.",
      "Any price change will not affect an order that has already been successfully confirmed, except where permitted or required by applicable law.",
      "5. Product Availability",
      "Our products may be released in limited or curated quantities.",
      "The availability of any product, size, colour, or variant is subject to stock.",
      "Adding an item to your shopping cart does not guarantee that the product will remain available until checkout is completed.",
      "6ix to Go may discontinue or modify products without prior notice.",
      "6. Orders",
      "When you place an order, you are making an offer to purchase the selected products.",
      "After placing an order, you may receive an order acknowledgement.",
      "An order confirmation does not necessarily mean that 6ix to Go has accepted every aspect of the order if circumstances require cancellation or correction.",
      "We reserve the right to cancel or refuse an order where reasonably necessary, including in cases involving:",
      "Product availability issues.",
      "Pricing or listing errors.",
      "Suspected fraudulent transactions.",
      "Unauthorised use of payment methods.",
      "Incorrect customer information.",
      "Duplicate or abnormal orders.",
      "Shipping restrictions.",
      "Other legitimate operational or legal reasons.",
      "Where an order is cancelled after payment has been received, an appropriate refund will be initiated in accordance with applicable law and our refund procedures.",
      "7. Payment",
      "Payments may be processed through third-party payment providers.",
      "You agree to provide accurate payment and billing information.",
      "6ix to Go does not guarantee uninterrupted availability of any particular payment method.",
      "Payment transactions may be subject to the terms and conditions of the relevant payment provider.",
      "8. Shipping and Delivery",
      "Shipping and delivery are governed by our Shipping Policy.",
      "Estimated delivery dates are indicative and may be affected by circumstances outside our reasonable control.",
      "9. Returns, Exchanges and Refunds",
      "Returns, exchanges, cancellations, and refunds are governed by our Return, Exchange & Refund Policy.",
      "Please review that policy before purchasing.",
      "Nothing in the policy is intended to remove any rights that cannot legally be excluded.",
      "10. Intellectual Property",
      "All content appearing on the 6ix to Go website, including but not limited to:",
      "Logos",
      "Brand names",
      "Graphics",
      "Illustrations",
      "Product artwork",
      "Photographs",
      "Videos",
      "Text",
      "Designs",
      "Product descriptions",
      "Website layout",
      "Icons",
      "Visual elements",
      "Software",
      "Original creative material",
      "is owned by or licensed to 6ix to Go unless otherwise stated.",
      "Such content is protected by applicable intellectual property laws.",
      "You may not copy, reproduce, modify, distribute, publish, transmit, sell, license, create derivative works from, or commercially exploit any 6ix to Go content without prior written permission.",
      "11. Brand and Trademark Rights",
      "\"6ix to Go\", associated logos, names, graphics, designs, slogans, and other brand elements may constitute trademarks or other intellectual property of 6ix to Go or its respective owners.",
      "Unauthorised use is prohibited.",
      "12. User Content",
      "If you submit reviews, photographs, comments, feedback, testimonials, social media content, or other material to 6ix to Go, you represent that:",
      "You have the right to submit the content.",
      "The content does not infringe third-party rights.",
      "The content is not unlawful, defamatory, misleading, abusive, or otherwise objectionable.",
      "To the extent permitted by applicable law, you grant 6ix to Go a non-exclusive, worldwide, royalty-free licence to use, reproduce, display, publish, adapt, and distribute such content for legitimate brand, marketing, promotional, and business purposes.",
      "13. Prohibited Website Use",
      "You agree not to:",
      "Use the website for unlawful purposes.",
      "Attempt to gain unauthorised access to the website or its systems.",
      "Interfere with website security or functionality.",
      "Introduce malicious code, viruses, or harmful software.",
      "Scrape, copy, or systematically extract website content without permission.",
      "Use another person's identity or payment information fraudulently.",
      "Place fraudulent or abusive orders.",
      "Attempt to circumvent security measures.",
      "Use website content for unauthorised commercial purposes.",
      "6ix to Go reserves the right to restrict or terminate access where reasonably necessary and permitted by law.",
      "14. Third-Party Links",
      "The website may contain links to third-party websites, applications, services, or social media platforms.",
      "These links are provided for convenience.",
      "6ix to Go does not control independent third-party websites and is not responsible for their content, security, availability, or privacy practices.",
      "15. Website Availability",
      "We aim to maintain reliable access to our website, but we do not guarantee that the website will always be available, uninterrupted, error-free, or free from viruses or other harmful components.",
      "We may temporarily suspend, modify, restrict, or discontinue portions of the website for maintenance, security, technical, operational, or other legitimate reasons.",
      "16. Disclaimer",
      "To the maximum extent permitted by applicable law, 6ix to Go does not guarantee that the website or all content available through it will always be accurate, complete, current, uninterrupted, or error-free.",
      "Nothing in these Terms excludes liability that cannot lawfully be excluded under applicable law.",
      "17. Limitation of Liability",
      "To the maximum extent permitted by applicable law, 6ix to Go shall not be liable for indirect, incidental, special, consequential, or unforeseeable losses arising from use of the website or products, except where such liability cannot legally be excluded.",
      "Nothing in these Terms limits or excludes any liability or consumer right that cannot legally be limited or excluded.",
      "18. Indemnity",
      "To the extent permitted by applicable law, you agree to indemnify and hold harmless 6ix to Go, its officers, employees, representatives, affiliates, service providers, and partners from claims, losses, liabilities, damages, and expenses arising from your unlawful use of the website, violation of these Terms, or infringement of third-party rights.",
      "19. Force Majeure",
      "6ix to Go shall not be responsible for delays or failures caused by events beyond its reasonable control, including natural disasters, severe weather, acts of government, strikes, civil disturbances, transportation disruptions, technical failures, pandemics, telecommunications failures, or other extraordinary circumstances.",
      "20. Governing Law",
      "These Terms shall be governed by and interpreted in accordance with the laws of India.",
      "Subject to applicable consumer protection laws and jurisdictional requirements, disputes shall be subject to the jurisdiction of the courts at Mumbai, Maharashtra.",
      "21. Consumer Rights",
      "Nothing in these Terms is intended to restrict, remove, or waive any consumer right or remedy that cannot legally be excluded under applicable law.",
      "22. Changes to these Terms",
      "6ix to Go may update these Terms from time to time.",
      "Changes will become effective when posted on the website unless otherwise stated.",
      "Your continued use of the website after an update constitutes acceptance of the revised Terms to the extent permitted by applicable law.",
      "23. Severability",
      "If any provision of these Terms is determined to be invalid, unlawful, or unenforceable, the remaining provisions will continue to apply to the extent permitted by law.",
      "24. Entire Agreement",
      "These Terms, together with the Privacy Policy, Shipping Policy, Return, Exchange & Refund Policy, and other policies expressly incorporated into these Terms, constitute the agreement governing your use of the website, subject to applicable law.",
      "."
    ]
  },
  "shipping-policy": {
    "title": "Shipping Policy",
    "body": [
      "Welcome to 6ix to Go.",
      "We are committed to delivering your order safely, securely,  This Shipping Policy explains how orders placed through the 6ix to Go website are processed, shipped, tracked, and delivered.",
      "By placing an order with 6ix to Go, you acknowledge and agree to the terms of this Shipping Policy.",
      "1. Order Processing",
      "All orders are processed after successful confirmation  which will be done via calling all the customers before the order is  processed",
      "Orders are generally processed and dispatched within 1–2 business days, excluding Sundays, public holidays, and circumstances beyond our reasonable control.",
      "During product launches, limited drops, promotional events, sale periods, or periods of exceptionally high order volume, processing may take additional time.",
      "6ix to Go reserves the right to extend processing timelines where necessary and will make reasonable efforts to communicate significant delays.",
      "2. Shipping Across India",
      "6ix to Go currently ships orders to addresses within India.",
      "Delivery availability may vary depending on the serviceability of the destination PIN code and the courier network available in that location.",
      "Certain remote, restricted, or difficult-to-service locations may require additional delivery time or may not be serviceable.",
      "3. Estimated Delivery Time",
      "Once an order has been dispatched, the estimated delivery time is generally:",
      "Metro cities: 2–5 business days",
      "Other serviceable locations: 3–7 business days",
      "Remote locations: 5–8 business days",
      "These are estimated timelines and are not guaranteed delivery dates.",
      "Delivery timelines may be affected by weather conditions, natural disasters, strikes, public holidays, transportation disruptions, courier delays, incorrect address information, or other circumstances outside 6ix to Go's reasonable control.",
      "4. Shipping Charges",
      "Applicable shipping charges, if any, will be displayed at checkout before you complete your purchase.",
      "6ix to Go may offer free shipping on selected orders, products, campaigns, or minimum order values. Any such offer will be subject to the conditions communicated at the time of purchase.",
      "5. Order Tracking",
      "Once your order has been dispatched, you may receive a shipping confirmation containing tracking information.",
      "You can use the tracking information provided to monitor the status of your shipment.",
      "Tracking information may take some time to become active after the package has been handed over to the courier.",
      "6. Delivery Attempts",
      "Our courier partners may make multiple delivery attempts before returning an undelivered shipment to our warehouse.",
      "Customers are responsible for ensuring that the shipping address, phone number, email address, and other delivery details provided at checkout are accurate and complete.",
      "If an order is returned to 6ix to Go because of an incorrect or incomplete address, recipient unavailability, refusal to accept delivery, or repeated failed delivery attempts, additional shipping charges may apply if the order is requested to be re-shipped.",
      "7. Incorrect Shipping Information",
      "Please carefully review your shipping details before completing your order.",
      "If you identify an incorrect address immediately after placing an order, contact us at krishj57@gmail.com as soon as possible.",
      "We will make reasonable efforts to update the shipping information before dispatch; however, we cannot guarantee that changes can be made after an order has entered the processing or shipping stage.",
      "6ix to Go shall not be responsible for delays or failed deliveries caused by inaccurate or incomplete information supplied by the customer.",
      "8. Delayed or Lost Shipments",
      "If your order appears to be delayed, please contact us at krishj57@gmail.com  with your order number.",
      "We will coordinate with the relevant logistics provider to investigate the shipment.",
      "If a shipment is officially declared lost by the courier, 6ix to Go will take appropriate steps to resolve the matter in accordance with applicable law and our customer service procedures.",
      "9. Damaged Packages",
      "If you receive a package that appears visibly damaged, tampered with, opened, or otherwise compromised, please contact 6ix to Go at krishj57@gmail.com as soon as reasonably possible.",
      "Where requested, customers may be required to provide photographs or videos of the package, shipping label, and product received so that the matter can be investigated.",
      "10. Cash on Delivery",
      "If Cash on Delivery (\"COD\") is offered on the website, COD availability may vary based on the customer's PIN code, order value, product, courier availability, or other applicable criteria.",
      "6ix to Go reserves the right to restrict COD availability where reasonably necessary to prevent fraud, misuse, repeated non-acceptance of orders, or operational losses.",
      "11. International Shipping",
      "6ix to Go currently does not offer international shipping.",
      "If international shipping becomes available, separate shipping charges, delivery timelines, customs duties, taxes, import restrictions, and other applicable charges may apply.",
      "12. Contact Us",
      "For shipping-related questions, please contact:",
      "6ix to Go",
      "Email: krishj57@gmail.com",
      "Phone/WhatsApp: 8108200988",
      "Address: D-5, RSC Rd Number 32, CHS, Samabhav Society, Gorai 2, Borivali West, Mumbai, Maharashtra 400091",
      "We are committed to helping you receive your 6ix to Go order safely and efficiently."
    ]
  },
  "contact-information": {
    "title": "Contact Information",
    "body": [
      "6ix to Go",
      "Email: krishj57@gmail.com",
      "Phone / WhatsApp: 8108200988",
      "Address: D-5, RSC Rd Number 32, CHS, Samabhav Society, Gorai 2, Borivali West, Mumbai, Maharashtra 400091",
      "India"
    ]
  }
};

export const aboutSections = [
  {
    "heading": "About 6ix to Go",
    "paragraphs": []
  },
  {
    "heading": "6ix to Go: Bringing the 2000s Back to India",
    "paragraphs": [
      "6ix to Go was born from a simple idea: India deserved more than mass-produced fashion.",
      "Founded by Krish Joshi, 6ix to Go started with a love for the culture, attitude, graphics, and individuality of the early 2000s. While studying in Los Angeles, Krish experienced a clothing culture where what you wore could feel personal, expressive, and different. The streets were full of bold graphics, nostalgic references, oversized silhouettes, and pieces that felt like they had a personality of their own.",
      "When he returned to India, he noticed something very different.",
      "Too often, hundreds or even thousands of identical T-shirts were being produced from the same designs. The result? Everyone started wearing the same thing.",
      "Krish wanted to change that.",
      "And that's where 6ix to Go began."
    ]
  },
  {
    "heading": "6ix Products. One Drop. No Ordinary Wardrobe.",
    "paragraphs": [
      "The name 6ix to Go comes directly from the brand's philosophy.",
      "Instead of flooding the market with endless collections, 6ix to Go releases 6ix products at a time.",
      "6ix pieces.",
      "6ix ideas.",
      "6ix chances to wear something different.",
      "Every drop is designed to feel intentional, limited, and exclusive—not like something pulled from an endless production line.",
      "Because we believe clothing should feel like a discovery.",
      "When a 6ix to Go piece is yours, it should feel like your piece, not something everyone else already has."
    ]
  },
  {
    "heading": "The 6ix to Go Philosophy",
    "paragraphs": [
      "We don't believe fashion should be about wearing what everyone else is wearing.",
      "We believe it's about finding something that feels like you.",
      "6ix to Go takes inspiration from the retro 2000s, Y2K culture, vintage graphics, streetwear, music, pop culture, and the unapologetic attitude of an era that wasn't afraid to stand out.",
      "But we aren't simply recreating the past.",
      "We're bringing the spirit of the 2000s into today's India.",
      "Our designs combine nostalgic aesthetics with contemporary streetwear, creating pieces that feel familiar, but never ordinary."
    ]
  },
  {
    "heading": "Made for the Ones Who Don't Want to Blend In",
    "paragraphs": [
      "6ix to Go is for people who look twice.",
      "For people who notice the graphic on a T-shirt.",
      "For people who care about what they wear, but don't want to look like everyone else.",
      "For the ones who grew up loving the 2000s or discovered the era long after it was gone.",
      "For the ones who believe a T-shirt can say something without saying a word.",
      "6ix to Go is clothing with character."
    ]
  },
  {
    "heading": "Why 6ix?",
    "paragraphs": [
      "6ix isn't just a number.",
      "It's the foundation of how we create.",
      "Rather than producing endless designs, we focus on a small number of pieces and give each one room to stand out.",
      "Every release is built around the idea of 6ix to go 6ix pieces available, 6ix designs to discover, and a constantly evolving archive of limited drops.",
      "The number keeps us focused.",
      "The limited approach keeps the pieces special.",
      "And the culture keeps us moving."
    ]
  },
  {
    "heading": "Our Take on Y2K & Retro Streetwear",
    "paragraphs": [
      "The early 2000s gave fashion something we think is worth bringing back: personality.",
      "Bold graphics.",
      "Oversized fits.",
      "Unexpected colours.",
      "Pop-culture references.",
      "Statement pieces.",
      "A little nostalgia.",
      "A lot of attitude.",
      "6ix to Go takes these influences and reinterprets them for the modern Indian streetwear scene.",
      "Our goal isn't to make costumes from the past.",
      "It's to create modern Y2K-inspired and retro streetwear that feels natural today."
    ]
  },
  {
    "heading": "Designed to Be Different",
    "paragraphs": [
      "In a world where mass production can make individuality difficult, we choose a different approach.",
      "We focus on limited designs, distinctive graphics, and carefully curated drops rather than overwhelming you with hundreds of options.",
      "Because having fewer choices can sometimes mean making a better choice.",
      "Every 6ix to Go release is an opportunity to discover something you haven't seen everywhere else.",
      "Less repetition. More expression."
    ]
  },
  {
    "heading": "From Los Angeles to India",
    "paragraphs": [
      "6ix to Go's story began with a cultural contrast.",
      "Krish Joshi experienced the streetwear and fashion culture of Los Angeles while studying there. What stood out wasn't just the clothing it was the confidence behind it.",
      "People wore clothes as an extension of who they were.",
      "That experience stayed with him.",
      "When he returned to India, he saw an opportunity to bring that same sense of individuality into the Indian fashion landscape while building something rooted in his own perspective.",
      "6ix to Go is the result.",
      "Inspired by LA. Built in India. Made for a generation that wants to stand apart."
    ]
  },
  {
    "heading": "More Than a T-Shirt",
    "paragraphs": [
      "At 6ix to Go, we don't see a graphic T-shirt as just another piece of clothing.",
      "A graphic can carry a memory.",
      "A colour can remind you of an era.",
      "A design can become the piece people remember you by.",
      "That's why we put thought into the details from the artwork and colour combinations to the overall feel of every drop.",
      "We want our pieces to become part of your story."
    ]
  },
  {
    "heading": "Our Promise",
    "paragraphs": [
      "We're not here to make the most clothes.",
      "We're here to make the right clothes.",
      "We'd rather release 6ix pieces people genuinely want than 6ix hundred pieces people forget.",
      "We'd rather create something distinctive than follow every trend.",
      "And we'd rather build a community around individuality than build a wardrobe around sameness.",
      "That's 6ix to Go.",
      "6ix pieces at a time.",
      "One different mindset.",
      "Welcome to 6ix to Go."
    ]
  }
];
